---
host:
  job-name : udr
  cpus-per-task: 5
timesteps: 7500000
eval_freq: 100000
now: 5
algo: sac
dr_percentage: 0.95
other_eval_env_dr: 0.95
gradient_steps: 1
compute_final_univariate_eval: false
verbose: 2
wandb: disabled

# Parameters to be set explicitly
env: null
performance_lb: null